# Generated by Django 5.2.3 on 2025-06-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseservice',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='baseservice',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
