# Generated by Django 5.2.3 on 2025-07-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_baseservice_description_alter_baseservice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseservice',
            name='service_photo',
            field=models.ImageField(default='services_photos/Cover.jpg', upload_to='services_photos'),
        ),
    ]
