# Generated by Django 5.2.4 on 2025-08-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_baseservice_service_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
