# Generated by Django 5.2.4 on 2025-08-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_baseservice_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseservice',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
