# Generated by Django 5.2.4 on 2025-07-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_baseservice_service_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseservice',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
