# Generated by Django 5.2.4 on 2025-12-31 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_baseservice_max_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseservice',
            old_name='max_price',
            new_name='euro_price',
        ),
        migrations.RenameField(
            model_name='baseservice',
            old_name='price',
            new_name='leva_price',
        ),
    ]
