# Generated by Django 5.2.4 on 2025-12-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_max_price_baseservice_euro_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseservice',
            name='euro_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseservice',
            name='leva_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
