# Generated by Django 5.2.4 on 2026-08-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_baseservice_euro_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseservice',
            name='category',
            field=models.CharField(choices=[('manicure', 'Маникюр'), ('pedicure', 'Педикюр')], default='manicure', max_length=20),
        ),
    ]
