# Generated by Django 5.2.3 on 2025-07-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientprofile_employeebio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
    ]
