# Generated by Django 5.2.4 on 2025-08-01 22:51

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_baseuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[accounts.validators.PhoneValidator()]),
        ),
    ]
