# Generated by Django 5.2.4 on 2025-08-02 04:03

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_baseuser_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos', validators=[accounts.validators.ImageSizeValidator(5)]),
        ),
    ]
