# Generated by Django 5.2.3 on 2025-07-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_baseuser_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
