# Generated by Django 5.2.4 on 2025-08-02 04:56

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_baseuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[accounts.validators.ImageSizeValidator(5)]),
        ),
    ]
