# Generated by Django 5.2.4 on 2025-07-06 14:49

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_baseuser_is_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employeebio',
            name='telephone_number',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='telephone_number',
            field=models.CharField(default=0, max_length=20, validators=[accounts.validators.PhoneValidator()]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeebio',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
