# Generated by Django 5.2.4 on 2025-07-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_clientprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Клиентски профил', 'verbose_name_plural': 'Клиентски профили'},
        ),
        migrations.AlterModelOptions(
            name='employeebio',
            options={'verbose_name': 'Служебен профил', 'verbose_name_plural': 'Служебни профили'},
        ),
    ]
