# Generated by Django 5.2.4 on 2025-08-04 08:53

import accounts.validators
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_baseuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='user_photos/', validators=[accounts.validators.ImageSizeValidator(5)]),
        ),
    ]
