# Generated by Django 5.2.4 on 2025-07-10 21:43

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebio',
            name='biography',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='employeebio',
            name='photo',
            field=models.ImageField(blank=True, upload_to='staff_photos', validators=[accounts.validators.ImageSizeValidator(5)]),
        ),
    ]
