# Generated by Django 5.2.4 on 2025-07-11 15:53

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_employeebio_biography_alter_employeebio_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='photo',
            field=models.FileField(blank=True, upload_to='defaults/default_user.png', validators=[accounts.validators.ImageSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='employeebio',
            name='photo',
            field=models.ImageField(blank=True, default='defaults/default_user.png', upload_to='staff_photos', validators=[accounts.validators.ImageSizeValidator(5)]),
        ),
    ]
