# Generated by Django 5.2.4 on 2025-07-11 15:56

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_clientprofile_photo_alter_employeebio_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='photo',
            field=models.FileField(blank=True, default='defaults/default_user.png', upload_to='user_photos', validators=[accounts.validators.ImageSizeValidator(5)]),
        ),
    ]
