# Generated by Django 5.2.4 on 2025-07-11 19:13

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_clientprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='employeebio',
            name='photo',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='photo',
            field=models.ImageField(blank=True, default='defaults/default_user.png', null=True, upload_to='user_photos', validators=[accounts.validators.ImageSizeValidator(5)]),
        ),
    ]
