# Generated by Django 5.2.4 on 2025-07-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_clientprofile_photo_remove_employeebio_photo_and_more'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebio',
            name='gallery_photo',
            field=models.ManyToManyField(related_name='gallery_photos', to='photos.galleryphoto'),
        ),
    ]
