# Generated by Django 5.2.4 on 2025-07-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_employeebio_gallery_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebio',
            name='gallery_photo',
        ),
    ]
