# Generated by Django 5.2.4 on 2025-07-17 00:26

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_employeebio_gallery_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebio',
            name='certificates',
            field=models.ImageField(blank=True, null=True, upload_to='certificates', validators=[accounts.validators.ImageSizeValidator(5)]),
        ),
    ]
