# Generated by Django 5.2.4 on 2025-07-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_employeebio_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebio',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
