# Generated by Django 5.2.4 on 2025-07-13 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_employeebio_gallery_photo'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryphoto',
            old_name='uploaded_at',
            new_name='upload_date',
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to='accounts.employeebio'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
