# Generated by Django 5.2.4 on 2025-08-02 04:56

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateimage',
            name='photo',
            field=models.ImageField(upload_to='', validators=[accounts.validators.ImageSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='photo',
            field=models.ImageField(upload_to='', validators=[accounts.validators.ImageSizeValidator(5)]),
        ),
    ]
