# Generated by Django 5.2.4 on 2025-08-02 09:37

import accounts.validators
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_certificateimage_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateimage',
            name='photo',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='', validators=[accounts.validators.ImageSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='photo',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='', validators=[accounts.validators.ImageSizeValidator(5)]),
        ),
    ]
