# Generated by Django 5.2.4 on 2025-07-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_rename_uploaded_at_galleryphoto_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
