# Generated by Django 5.2.4 on 2025-07-17 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_employeebio_certificates'),
        ('photos', '0004_certificateimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateimage',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='accounts.employeebio'),
        ),
    ]
