# Generated by Django 5.2.4 on 2025-07-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_certificateimage_uploader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateimage',
            options={'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификати'},
        ),
    ]
