# Generated by Django 5.2.4 on 2025-07-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_certificateimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'verbose_name': 'Галерия'},
        ),
    ]
