# Generated by Django 5.2.4 on 2025-07-24 09:51

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_galleryphoto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateimage',
            name='photo',
            field=models.ImageField(upload_to='certificates', validators=[accounts.validators.ImageSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='photo',
            field=models.ImageField(upload_to='gallery_photos', validators=[accounts.validators.ImageSizeValidator(5)]),
        ),
    ]
