# Generated by Django 5.2.4 on 2025-07-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_baseuser_is_client'),
        ('appointments', '0002_appointment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='dayoff',
            unique_together={('employee', 'date')},
        ),
    ]
