# Generated by Django 5.2.4 on 2025-07-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_dayoff_date_alter_dayoff_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Записване на час', 'verbose_name_plural': 'Записване на часове'},
        ),
    ]
