# Generated by Django 5.2.4 on 2025-07-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
