# Generated by Django 5.2.4 on 2025-07-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayoff',
            options={'verbose_name': 'Почивен ден', 'verbose_name_plural': 'Почивни дни'},
        ),
    ]
